image:
   name: grindwiseinc/propertymgmt.portfoliomgmt.house.register.pipeline:1.0  
   username: $DOCKER_HUB_USERNAME
   password: $DOCKER_HUB_PASSWORD
   email: $EMAIL
   ports: "27017:27017"

pipelines:
  default:
    - step:
        script:
          # start mongod
          - mongod --fork --logpath /var/log/mongod.log

          # build jar
          - gradle clean shadowJar

          # solitary tests
          - gradle solitaryTests

          # unit tests
          - gradle unitTests

          # acceptance tests
          - gradle acceptanceTests

          # checkstyle
          - gradle checkstyleMain

          # findbugs
          - gradle findbugsMain

          # docker - create image and push
          - gradle dockerCopy
          - cd docker/runtime_container
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker build --force-rm --tag=grindwiseinc/propertymgmt.house.register:$BITBUCKET_COMMIT .
          - docker push grindwiseinc/propertymgmt.house.register:$BITBUCKET_COMMIT

options:
  docker: true

