image:
  name: grindwiseinc/propertymgmt.portfoliomgmt.house.register.pipeline:1.0  
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $EMAIL
  ports: "27017:27017"

pipelines:
  default:
    - step:
        name: commit stage

        script:
          # start mongod
          - mongod --fork --logpath /var/log/mongod.log

          # build jar
          - gradle clean shadowJar

          # solitary tests
          - gradle solitaryTests

          # unit tests
          - gradle unitTests

          # checkstyle
          - gradle checkstyleMain

          # findbugs
          - gradle findbugsMain

          # store binary artifact (jar)
          - gradle -DrepoId=$BINARY_REPO_USER -DrepoPassword=$BINARY_REPO_PASS publish

    - step:
          name: acceptance stage

          deployment: test

          script:
            # download uber jar
            - gradle downloadUberJar

            # acceptance tests
            #- gradle acceptanceTests

            # docker - create image and push
            #- gradle dockerCopy
            #- cd docker/runtime_image
            #- docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            #- docker build --force-rm --tag=grindwiseinc/propertymgmt.portfoliomgmt.house.register:$BITBUCKET_COMMIT .
            #- docker push grindwiseinc/propertymgmt.portfoliomgmt.house.register:$BITBUCKET_COMMIT

options:
  docker: true

