image:
  name: grindwiseinc/propertymgmt.portfoliomgmt.house.register.pipeline:1.0  
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $EMAIL
  ports: "27017:27017"

pipelines:
  default:
    - step:
        name: commit stage

        script:
          # build jar
          - gradle clean shadowJar

          # solitary tests
          #- gradle solitaryTests

          # unit tests
          #- gradle unitTests

          # checkstyle
          #- gradle checkstyleMain

          # findbugs
          #- gradle findbugsMain

        artifacts:
          # copy artifacts for following steps
          - build/libs/**

    - step:
          name: acceptance stage

          script:
            # start mongod
            - mongod --fork --logpath /var/log/mongod.log

            # acceptance tests
            #- gradle acceptanceTests
            #

    - step:
          name: scan for security vulnerabilities

          script:
            # download & scan
            - /usr/lib/curl -ssl https://download.sourceclear.com/ci.sh | sh

    - step:
          name: create image and push

          script:
            # docker - create image and push
            - gradle dockerCopy
            #- cd docker/runtime_image
            #- docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            #- docker build --force-rm --tag=grindwiseinc/propertymgmt.portfoliomgmt.house.register:$BITBUCKET_COMMIT .
            #- docker push grindwiseinc/propertymgmt.portfoliomgmt.house.register:$BITBUCKET_COMMIT

    - step:
          name: deploy to staging

          deployment: staging

          script:
            # deploy service
            - gradle deploy -Pdeployer_user=$DEPLOYER_USER -Pdeployer_password=$DEPLOYER_PASS

    - step:
          name: smoke test staging

          script:
            # execute smoke tests
            - gradle smoke

options:
  docker: true

