image:
  name: grindwiseinc/propertymgmt.portfoliomgmt.house.register.pipeline:1.0
  deployer_access_key_id_and_value: $DEPLOYER_ACCESS_KEY_ID_AND_VALUE
  deployer_secret_access_key_and_value: $DEPLOYER_SECRET_ACCESS_KEY_AND_VALUE
  username: $DOCKER_HUB_USERNAME
  password: $DOCKER_HUB_PASSWORD
  email: $EMAIL
  ports: "27017:27017"

pipelines:
  default:
    - step:
        name: commit stage

        script:
          - echo "access id: ${deployer_access_key_id_and_value}"
          - echo "secret key: ${deployer_secret_access_key_and_value}"

          # build jar
          - gradle clean shadowJar

          # solitary tests
          #- gradle solitaryTests

          # unit tests
          #- gradle unitTests

          # checkstyle
          #- gradle checkstyleMain

          # spotbugs
          #- gradle spotbugsMain

        artifacts:
          # copy artifacts for following steps
          - build/libs/**

    - step:
          name: acceptance stage

          script:
            # start mongod
            #- mongod --fork --logpath /var/log/mongod.log

            # acceptance tests
            #- gradle acceptanceTests

    - step:
          name: software composition analysis - scan for 3rd party security vulnerabilities

          script:
            # download & scan
            #- gradle srcclr
            - echo "sca"

    - step:
          name: static application security testing - scan for homegrown security vulnerabilities
          
          script:
          # scan our code
          - echo "scanning our code"

    - step:
          name: create image and push

          script:
            - echo "create image and push"
            # docker - create image and push
            #- gradle dockerCopy
            #- cd docker/runtime_image
            #- docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            #- docker build --force-rm --tag=grindwiseinc/propertymgmt.portfoliomgmt.house.register:$BITBUCKET_COMMIT .
            #- docker push grindwiseinc/propertymgmt.portfoliomgmt.house.register:$BITBUCKET_COMMIT

    - step:
          name: spin up staging infrastructure

          script:
            - echo "spinning up resources"

    - step:
          name: deploy to staging

          deployment: staging

          script:
            - gradle packageDistribution

            - gradle deploy -Pdeployer_access_id=$deployer_access_key_id_and_value \
                            -Pdeployer_secret_key=$deployer_secret_access_key_and_value

    - step:
          name: smoke test staging

          script:
            # execute smoke tests
            - gradle smoke

options:
  docker: true

