version: 0.2

phases:

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...

  build:
    commands:
      - echo Build started on `date`
      - gradlew clean shadowJar 

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/propertymgmt.portfoliomgmt.house.register-1.0.0.jar 
