#!/bin/bash

export version=1.0.0
export persistent_store_name=house_properties
export persistent_store_username=""
export persistent_store_password=""
export persistent_store_host=localhost
export persistent_store_port=27017
export persistent_collection_name=houses
