addressAuthenticatorID:
addressAuthenticatorToken:

server:
  applicationContextPath: /propertymgmt
  rootPath: /

  applicationConnectors:
    - type: http
      port: 7085
  adminConnectors:
    - type: http
      port: 7086

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG

  # Logger-specific levels.
  loggers:
    "PojoCodec": DEBUG
    "com.gws": DEBUG


  appenders:
    - type: console
      threshold: DEBUG 
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC
      target: stdout

    - type: file
      currentLogFilename: /opt/propertymgmt/register-house-service/register.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /opt/propertymgmt/register-house-service/register-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"

    - type: logstash-tcp
      threshold: DEBUG 
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      timeZone: UTC
      host: 172.17.0.2
      port: 5044

#      fieldNames:
#        message: msg
#        timestamp: log_date

